version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
    restart: always
    command: bash /entrypoint.sh
    networks:
      - laravel-app

networks:
  laravel-app:
